### ISSUE TITLE
[Suggestion]: Allow players to equip the Hang Glider in a separate Trinkets slot

### ISSUE THREAD

**Issue by vico93** [Fuzss/hangglider#4]
### Suggestion (Required)

Basically allow the hang glider to be equipped in the same slot [Elytra Slot](https://modrinth.com/mod/elytra-slot) ([GH](https://github.com/illusivesoulworks/elytraslot)) uses for Elytras.

**Comment by Fuzss** [comment]
Thanks for the suggestion. That wouldn't work since you need to activate the glider from your hand for it to open up. Also it doesn't make much sense as a Trinket to me since you are holding it in your hands. It's also intentional that your hands can't do anything else while gliding, you are holding on to the glider after all.
